name: Build and Push to JFrog Artifactory

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package

      - name: Upload artifact to JFrog Artifactory
        env:
          ARTIFACTORY_URL: http://13.232.125.253:8082/artifactory
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        run: |
          curl -u "$ARTIFACTORY_USERNAME:$ARTIFACTORY_PASSWORD" -T target/*.war "$ARTIFACTORY_URL/my-repo-name/"
