name: Java CI with Gradle

on:
  push:
    branches: [ "newfeature22" ]
  pull_request:
    branches: [ "newfeature22" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.12.1'

      - name: Debug Gradle Wrapper Presence
        run: ls -lah  # ✅ Check if gradlew exists

      - name: Grant execute permission to Gradle Wrapper
        run: chmod +x gradlew  # ✅ Fix permission issue

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Build without Wrapper (Fallback)
        if: failure()
        run: gradle build
