name: Java CI with Gradle

on:  # ✅ This section defines when the workflow should run
  push:
    branches: [ "newfeature" ]
  pull_request:
    branches: [ "newfeature" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.12.1'

      - name: Grant execute permission to Gradle Wrapper
        run: chmod +x gradlew  # Fixes permission issue

      - name: Build with Gradle Wrapper
        run: ./gradlew build
